---
simulation:
  iterations: 10000
resourceProperties:
  smallResources: 20
  smallObjectWidth: 0.4
  smallObjectHeight: 0.4
  smallObjectMass: 1.0
  maxSmallObjectPushingBots: 1
  largeResources: 20
  largeObjectWidth: 0.6
  largeObjectHeight: 0.6
  largeObjectMass: 4.0
  maxLargeObjectPushingBots: 2
scoring:
  fitnessFunction: za.redbridge.simulator.ea.DefaultFitnessFunction
factories:
  resourceFactory: za.redbridge.simulator.factories.ConfigurableResourceFactory
  robotFactory: za.redbridge.simulator.factories.HomogeneousRobotFactory
robots:
  numRobots: 20
  mass: 0.7
  radius: 0.15
  colour: 0, 0, 0
